import "./globals.css";

import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import Script from "next/script";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { SITE_URL } from "@/lib/site";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

// Google Analytics Measurement ID (overridable via env for non-prod environments)
const GA_MEASUREMENT_ID =
  process.env.NEXT_PUBLIC_GA_ID || "G-3G556LZGJB";

// SITE_URL (canonical www origin) is imported from lib/site.ts. Used as
// `metadataBase` so OpenGraph / Twitter card image URLs resolve to absolute
// URLs even when set as site-relative paths.

// Note: the default OG/Twitter image is generated by `app/opengraph-image.tsx`.
// Next.js wires up the `og:image` and `twitter:image` meta tags automatically
// from that file convention, so we don't list `images` here.

const SITE_TITLE = "Kekuleon Research and Training Center | KRTC";
const SITE_DESCRIPTION =
  "Bridging the Theory-Practice Gap in Science Education. Integrated research, laboratory training, industry collaboration, and community engagement for the next generation of scientists in Bangladesh.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: "%s | KRTC",
  },
  description: SITE_DESCRIPTION,
  keywords: [
    "KRTC",
    "Kekuleon",
    "Research Center Bangladesh",
    "Science Training",
    "Laboratory Training",
    "Applied Chemistry",
    "Pharmaceutical Sciences",
    "Materials Science",
    "Textile Testing",
    "Nursing Training",
    "PhD Programs Bangladesh",
    "IELTS Preparation",
    "Sirajganj",
  ],
  authors: [{ name: "Md. Zakaria Hossain" }],
  openGraph: {
    title: SITE_TITLE,
    description:
      "Bridging the Theory-Practice Gap in Science Education in Bangladesh",
    url: SITE_URL,
    siteName: "KRTC",
    locale: "en_US",
    type: "website",
    // `images` intentionally omitted — `app/opengraph-image.tsx` provides
    // the default og:image for the entire site.
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description:
      "Bridging the Theory-Practice Gap in Science Education in Bangladesh",
    // No explicit `images` — Twitter falls back to og:image, which is
    // generated by `app/opengraph-image.tsx`.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: "/icon.png",
};

// JSON-LD Organization schema. Helps Google show rich-snippet info
// (logo, social profiles, contact) in search results and knowledge
// panels. The site-wide markup lives in the root layout so every page
// inherits it; per-page schemas (Article, Person) can be added later in
// individual pages.
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Kekuleon Research and Training Center",
  alternateName: "KRTC",
  url: SITE_URL,
  logo: `${SITE_URL}/images/logo.png`,
  description: SITE_DESCRIPTION,
  foundingLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressCountry: "BD",
      addressRegion: "Sirajganj",
    },
  },
  sameAs: [
    "https://www.facebook.com/kekuleon",
    "https://www.linkedin.com/company/kekuleon",
  ],
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "general",
    email: "kekuleoninfo@gmail.com",
    availableLanguage: ["English", "Bengali"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          `}
        </Script>
        <Script
          id="organization-jsonld"
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationJsonLd),
          }}
        />
      </head>
      <body className="font-sans antialiased">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
