// =============================================
// KRTC Student Directory Data
// Batch Format: SSC [Year] — Batch [Number]
// Student ID Format: [BatchNum][3-digit serial]
// Scholarship %: Tuition fee discount percentage
// Photo: Optional — path to student image
// =============================================

export interface Student {
  name: string;
  id: string;
  school: string;
  scholarship: number;
  gender: "male" | "female";
  photo?: string; // e.g. "/images/students/28001.jpg"
  batch: string; // e.g. "Batch 28"
}

export interface Batch {
  batchNumber: number;
  sscYear: number;
  label: string;
  students: Student[];
}

// ===== SSC 2026 — Batch 26 =====
const batch26: Batch = {
  batchNumber: 26,
  sscYear: 2026,
  label: "Batch 26",
  students: [
    // ———— From Admission Forms ————
    {
      // photo: "/images/students/26001.jpg",
      name: "Mst. Asma Ul Husna",
      id: "26001",
      batch: "26 batch",
      school: "Subarnoganthi High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26002.jpg",
      name: "Mst. Nupur Khatun",
      id: "26002",
      batch: "26 batch",
      school: "Subarnoganti High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26003.jpg",
      name: "Mst. Nusrat Jahan",
      id: "26003",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26004.jpg",
      name: "Md. Maruf Bin Jihad",
      id: "26004",
      batch: "26 batch",
      school: "Char Khokshabari High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26005.jpg",
      name: "Mst. Medha Khatun",
      id: "26005",
      batch: "26 batch",
      school: "Tarakandi High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26006.jpg",
      name: "Md. Siyam Sarker",
      id: "26006",
      batch: "26 batch",
      school: "Chorachara High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26007.jpg",
      name: "Mst. Saima Jahan",
      id: "26007",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26008.jpg",
      name: "Mushfika Mou",
      id: "26008",
      batch: "26 batch",
      school: "Raigonj Upozila Sadar Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26009.jpg",
      name: "Israt Jahan Anika",
      id: "26009",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26010.jpg",
      name: "Mysha Muftakim",
      id: "26010",
      batch: "26 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26011.jpg",
      name: "Mst. Jannatul Mawa",
      id: "26011",
      batch: "26 batch",
      school: "Garudaha High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26012.jpg",
      name: "Umme Habiba",
      id: "26012",
      batch: "26 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26013.jpg",
      name: "Mst. Fatema Khatun Akhi",
      id: "26013",
      batch: "26 batch",
      school: "Saraitoil High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26014.jpg",
      name: "Mst. Shilpy Khatun",
      id: "26014",
      batch: "26 batch",
      school: "Garudaha High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26015.jpg",
      name: "Mst. Shifa Khatun",
      id: "26015",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26016.jpg",
      name: "Mst. Fatema Khatun",
      id: "26016",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26017.jpg",
      name: "Mst. Jannatul",
      id: "26017",
      batch: "26 batch",
      school: "Garudaha High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26018.jpg",
      name: "Mst. Sanjida Islam",
      id: "26018",
      batch: "26 batch",
      school: "",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26019.jpg",
      name: "Khadija Talukder",
      id: "26019",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26020.jpg",
      name: "Rukaiya Jannat",
      id: "26020",
      batch: "26 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26021.jpg",
      name: "Mst. Ayesha Khatun",
      id: "26021",
      batch: "26 batch",
      school: "Subornagati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26022.jpg",
      name: "Md. Showrov Ahmed",
      id: "26022",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26023.jpg",
      name: "Most. Limu Khatun",
      id: "26023",
      batch: "26 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26024.jpg",
      name: "Mst. Elma Khatun",
      id: "26024",
      batch: "26 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26025.jpg",
      name: "Most. Shagorika Khatun",
      id: "26025",
      batch: "26 batch",
      school: "Shaheed Rafiqul Model School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26026.jpg",
      name: "Md. Arafat Ahmed Rizvy",
      id: "26026",
      batch: "26 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26027.jpg",
      name: "Mst. Mahiya Akter",
      id: "26027",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26028.jpg",
      name: "Mst. Joba Khatun",
      id: "26028",
      batch: "26 batch",
      school: "Shaheed Rafiqul Model School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26029.jpg",
      name: "Md. Rezaul Karim",
      id: "26029",
      batch: "26 batch",
      school: "Gandhail Ratankandi Union Ali Ahmmed High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26030.jpg",
      name: "Md. Arafat Mirza",
      id: "26030",
      batch: "26 batch",
      school: "Garudaha High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26031.jpg",
      name: "SM. Shakib Al-Hassan",
      id: "26031",
      batch: "26 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "male",
    },

    // ———— From Handwritten List (new students not in admission forms) ————
    {
      // photo: "/images/students/26032.jpg",
      name: "Salman Farsi",
      id: "26032",
      batch: "26 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26033.jpg",
      name: "Rifat Hasan",
      id: "26033",
      batch: "26 batch",
      school: "Gandhail High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26034.jpg",
      name: "Abdul Owakil",
      id: "26034",
      batch: "26 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26035.jpg",
      name: "Emon Rana",
      id: "26035",
      batch: "26 batch",
      school: "Saraitoil High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26036.jpg",
      name: "Riyad Ahmed",
      id: "26036",
      batch: "26 batch",
      school: "Saraitoil High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26037.jpg",
      name: "Md. Al Arafat Khan",
      id: "26037",
      batch: "26 batch",
      school: "Tarakandi High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26038.jpg",
      name: "Abdullah Sheik",
      id: "26038",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26039.jpg",
      name: "Shibly Sadik",
      id: "26039",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26040.jpg",
      name: "Mobassira Siddika",
      id: "26040",
      batch: "26 batch",
      school: "Dattobari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26041.jpg",
      name: "Partho Datta",
      id: "26041",
      batch: "26 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26042.jpg",
      name: "Tamim Hasan",
      id: "26042",
      batch: "26 batch",
      school: "Bhatpeary High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26043.jpg",
      name: "Bayezid Hasan",
      id: "26043",
      batch: "26 batch",
      school: "Gandhail High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26044.jpg",
      name: "Mst. Sathi Khatun",
      id: "26044",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26045.jpg",
      name: "Hazrat Ali",
      id: "26045",
      batch: "26 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26046.jpg",
      name: "Srabonti Rani",
      id: "26046",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26047.jpg",
      name: "Mst. Tajmohol Khatun",
      id: "26047",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26048.jpg",
      name: "Md. Abdullah Al Mamun",
      id: "26048",
      batch: "26 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26049.jpg",
      name: "Mst. Sudia Afrin",
      id: "26049",
      batch: "26 batch",
      school: "Saraitoil High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26050.jpg",
      name: "Md. Monir Hossain",
      id: "26050",
      batch: "26 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26051.jpg",
      name: "Mst. Humaira Khatun",
      id: "26051",
      batch: "26 batch",
      school: "Tarakandi High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26052.jpg",
      name: "Mst. Keyamoni Khatun",
      id: "26052",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26053.jpg",
      name: "Afsana Akter Mim",
      id: "26053",
      batch: "26 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26054.jpg",
      name: "Hreedita Talukder Reetu",
      id: "26054",
      batch: "26 batch",
      school: "Saraitoil High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26055.jpg",
      name: "Md. Shjakhaeat Hossain Tamim",
      id: "26055",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26056.jpg",
      name: "Mst. Mithila Khatun",
      id: "26056",
      batch: "26 batch",
      school: "Dattabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26057.jpg",
      name: "Habibullah",
      id: "26057",
      batch: "26 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26058.jpg",
      name: "Rifat Hasan Naeem",
      id: "26058",
      batch: "26 batch",
      school: "Saraitoil High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26059.jpg",
      name: "Sujoy Malo",
      id: "26059",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26060.jpg",
      name: "Md. Faysal Ahmed",
      id: "26060",
      batch: "26 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26061.jpg",
      name: "Umme Salma",
      id: "26061",
      batch: "26 batch",
      school: "Dattabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26062.jpg",
      name: "Nirob Datta",
      id: "26062",
      batch: "26 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26063.jpg",
      name: "Md. Tanvir Rahman Shishir",
      id: "26063",
      batch: "26 batch",
      school: "Gandhail Ratankandi Union Ali Ahmmed High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26064.jpg",
      name: "Md. Saim Rahman",
      id: "26064",
      batch: "26 batch",
      school: "Gandhail Ratankandi Union Ali Ahmmed High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/26065.jpg",
      name: "Mst. Fatema Khatun",
      id: "26065",
      batch: "26 batch",
      school: "Millennium School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/26066.jpg",
      name: "Sourov Kumar",
      id: "26066",
      batch: "26 batch",
      school: "Subornogati High School",
      scholarship: 0,
      gender: "male",
    },
  ],
};

// ===== SSC 2027 — Batch 27 =====
const batch27: Batch = {
  batchNumber: 27,
  sscYear: 2027,
  label: "Batch 27",
  students: [
    // ———— Page 1 (01–18) ————
    {
      // photo: "/images/students/27001.jpg",
      name: "Most. Nupur Khatun",
      id: "27001",
      batch: "27 batch",
      school: "Boyra Vennabari High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27002.jpg",
      name: "Md. Yeashin Arafat",
      id: "27002",
      batch: "27 batch",
      school: "Vet Piari J.R.S High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27003.jpg",
      name: "Mst. Asha Khatun",
      id: "27003",
      batch: "27 batch",
      school: "Horina Bagbati Girls High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27004.jpg",
      name: "Mst. Sumiya Akter",
      id: "27004",
      batch: "27 batch",
      school: "Horina Bagbati Girls High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27005.jpg",
      name: "Md. Arefin Siddiq",
      id: "27005",
      batch: "27 batch",
      school: "Khokshabari High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27006.jpg",
      name: "Md. Raj Islam",
      id: "27006",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27007.jpg",
      name: "Mst. Jannati Khatun",
      id: "27007",
      batch: "27 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27008.jpg",
      name: "Rijoyana Roushan",
      id: "27008",
      batch: "27 batch",
      school: "Saleha Ishak Girls High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27009.jpg",
      name: "Homayara Jannat",
      id: "27009",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27010.jpg",
      name: "Lopa Roy",
      id: "27010",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27011.jpg",
      name: "Mst. Sadia Tabassum",
      id: "27011",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27012.jpg",
      name: "Md. Jihad Rana",
      id: "27012",
      batch: "27 batch",
      school: "Bhatpeary J.R.S High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27013.jpg",
      name: "Md. Imran Hasan Ratul",
      id: "27013",
      batch: "27 batch",
      school: "Bhatpeary J.R.S High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27014.jpg",
      name: "Md. Jubayed Hossain",
      id: "27014",
      batch: "27 batch",
      school: "Bhatpeary J.R.S High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27015.jpg",
      name: "Md. Mridul Hasan Mehedi",
      id: "27015",
      batch: "27 batch",
      school: "Bhatpeary J.R.S High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27016.jpg",
      name: "Mst. Rukaiya Khatun",
      id: "27016",
      batch: "27 batch",
      school: "Boyra Vennabari High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27017.jpg",
      name: "Mst. Murshida Khatun",
      id: "27017",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27018.jpg",
      name: "Mst. Farzana Akter Rafiya",
      id: "27018",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 100,
      gender: "female",
    },

    // ———— Page 2 (19–35) ————
    {
      // photo: "/images/students/27019.jpg",
      name: "Mst. Jannatul Ferdaus Mem",
      id: "27019",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 60,
      gender: "female",
    },
    {
      // photo: "/images/students/27020.jpg",
      name: "Mst. Rabiya Khatun",
      id: "27020",
      batch: "27 batch",
      school: "Boyra Vennabari High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27021.jpg",
      name: "Mst. Mashruta Khatun",
      id: "27021",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 60,
      gender: "female",
    },
    {
      // photo: "/images/students/27022.jpg",
      name: "Annona Rani",
      id: "27022",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 60,
      gender: "female",
    },
    {
      // photo: "/images/students/27023.jpg",
      name: "Shadhin",
      id: "27023",
      batch: "27 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 70,
      gender: "male",
    },
    {
      // photo: "/images/students/27024.jpg",
      name: "Md. Alvy Hossain Alif",
      id: "27024",
      batch: "27 batch",
      school: "Bhatpeary J.R.S. High School",
      scholarship: 75,
      gender: "male",
    },
    {
      // photo: "/images/students/27025.jpg",
      name: "Mst. Fatema Akter",
      id: "27025",
      batch: "27 batch",
      school: "Bahuka High School",
      scholarship: 50,
      gender: "female",
    },
    {
      // photo: "/images/students/27026.jpg",
      name: "Sidratul Muntaha",
      id: "27026",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 65,
      gender: "female",
    },
    {
      // photo: "/images/students/27027.jpg",
      name: "Tasfiha Tabassum Tohfa",
      id: "27027",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 65,
      gender: "female",
    },
    {
      // photo: "/images/students/27028.jpg",
      name: "Yeamin Hasan",
      id: "27028",
      batch: "27 batch",
      school: "Vet Piari J.R.S High School",
      scholarship: 65,
      gender: "male",
    },
    {
      // photo: "/images/students/27029.jpg",
      name: "Moklesur Ahmad",
      id: "27029",
      batch: "27 batch",
      school: "Vet Piari J.R.S High School",
      scholarship: 60,
      gender: "male",
    },
    {
      // photo: "/images/students/27030.jpg",
      name: "Jannatul Ferdaus Prova",
      id: "27030",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27031.jpg",
      name: "Mst. Adia Akter",
      id: "27031",
      batch: "27 batch",
      school: "Tarakandi High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27032.jpg",
      name: "Rabbi",
      id: "27032",
      batch: "27 batch",
      school: "Tarakandi High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27033.jpg",
      name: "Jubayer Rahman",
      id: "27033",
      batch: "27 batch",
      school: "Dattabari High School",
      scholarship: 65,
      gender: "male",
    },
    {
      // photo: "/images/students/27034.jpg",
      name: "Sabbir Rahman",
      id: "27034",
      batch: "27 batch",
      school: "Kazipur Ranidinmoni High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27035.jpg",
      name: "Md. Osman Haruni",
      id: "27035",
      batch: "27 batch",
      school: "Char Son Gasha Fazil Degree Madrasha",
      scholarship: 70,
      gender: "male",
    },

    // ———— Page 3 (36–46 numbered + unnumbered) ————
    {
      // photo: "/images/students/27036.jpg",
      name: "Naim Hasan",
      id: "27036",
      batch: "27 batch",
      school: "",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/27037.jpg",
      name: "Anamul Hoque",
      id: "27037",
      batch: "27 batch",
      school: "Char Son Gasha Fazil Degree Madrasha",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/27038.jpg",
      name: "Dipti Paddar",
      id: "27038",
      batch: "27 batch",
      school: "Char Son Gasha Fazil Degree Madrasha",
      scholarship: 50,
      gender: "female",
    },
    {
      // photo: "/images/students/27039.jpg",
      name: "Abdur Razzak",
      id: "27039",
      batch: "27 batch",
      school: "Saraitoil High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27040.jpg",
      name: "Mehedi Hasan",
      id: "27040",
      batch: "27 batch",
      school: "Bahuka High School",
      scholarship: 90,
      gender: "male",
    },
    {
      // photo: "/images/students/27041.jpg",
      name: "Rabea Taposi",
      id: "27041",
      batch: "27 batch",
      school: "Boyra Vennabari High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27042.jpg",
      name: "Ayesha Siddika Jui",
      id: "27042",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27043.jpg",
      name: "Emon Shiek",
      id: "27043",
      batch: "27 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/27044.jpg",
      name: "Isratul Jannat Urmi",
      id: "27044",
      batch: "27 batch",
      school: "Horina Bagbati High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/27045.jpg",
      name: "Fatema Akter",
      id: "27045",
      batch: "27 batch",
      school: "Bahuka High School",
      scholarship: 80,
      gender: "female",
    },
    {
      // photo: "/images/students/27046.jpg",
      name: "Md. Mousalein",
      id: "27046",
      batch: "27 batch",
      school: "Char Son Gasha Fazil Degree Madrasha",
      scholarship: 70,
      gender: "male",
    },

    // ———— Unnumbered entries (page 3 bottom) ————
    {
      // photo: "/images/students/27047.jpg",
      name: "Most. Moriom Khatun",
      id: "27047",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/27048.jpg",
      name: "Mst. Lamiya Khatun",
      id: "27048",
      batch: "27 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/27049.jpg",
      name: "Most. Forjahana Khatun",
      id: "27049",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/27050.jpg",
      name: "Israt Jahan Mitu",
      id: "27050",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/27051.jpg",
      name: "Riya Moni",
      id: "27051",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/27052.jpg",
      name: "Most. Taslima Khatun",
      id: "27052",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/27053.jpg",
      name: "Most. Shimu Khatun",
      id: "27053",
      batch: "27 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/27054.jpg",
      name: "Mohima Sarker Moon",
      id: "27054",
      batch: "27 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "female",
    },
  ],
};

// ===== SSC 2028 — Batch 28 =====
const batch28: Batch = {
  batchNumber: 28,
  sscYear: 2028,
  label: "Batch 28",
  students: [
    // ———— Text list (28001–28016) ————
    {
      // photo: "/images/students/28001.jpg",
      name: "Md. Nahian Rabi",
      id: "28001",
      batch: "28 batch",
      school: "Boyra Vennabari High School",
      scholarship: 37,
      gender: "male",
    },
    {
      // photo: "/images/students/28002.jpg",
      name: "Md. Motaleb",
      id: "28002",
      batch: "28 batch",
      school: "Tarakandi High School",
      scholarship: 40,
      gender: "male",
    },
    {
      // photo: "/images/students/28003.jpg",
      name: "Shaik Zidan",
      id: "28003",
      batch: "28 batch",
      school: "Tarakandi High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/28004.jpg",
      name: "Md. Salehin Islam",
      id: "28004",
      batch: "28 batch",
      school: "Tarakandi High School",
      scholarship: 85,
      gender: "male",
    },
    {
      // photo: "/images/students/28005.jpg",
      name: "Md. Mehedi Hasan",
      id: "28005",
      batch: "28 batch",
      school: "Bhatpiary J.R.S High School",
      scholarship: 100,
      gender: "male",
    },
    {
      // photo: "/images/students/28006.jpg",
      name: "Md. Naim Islam",
      id: "28006",
      batch: "28 batch",
      school: "Bhatpiary J.R.S High School",
      scholarship: 43,
      gender: "male",
    },
    {
      // photo: "/images/students/28007.jpg",
      name: "Shamima Afren Mim",
      id: "28007",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 33,
      gender: "female",
    },
    {
      // photo: "/images/students/28008.jpg",
      name: "Sumaiya Khatun",
      id: "28008",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 33,
      gender: "female",
    },
    {
      // photo: "/images/students/28009.jpg",
      name: "Jannatun Ferdosy",
      id: "28009",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 37,
      gender: "female",
    },
    {
      // photo: "/images/students/28010.jpg",
      name: "Md. Parvej Ali",
      id: "28010",
      batch: "28 batch",
      school: "Bhatpiary J.R.S High School",
      scholarship: 43,
      gender: "male",
    },
    {
      // photo: "/images/students/28011.jpg",
      name: "Nafiz Hasan Nabid",
      id: "28011",
      batch: "28 batch",
      school: "Bhatpiary J.R.S High School",
      scholarship: 43,
      gender: "male",
    },
    {
      // photo: "/images/students/28012.jpg",
      name: "Md. Likhon Reja",
      id: "28012",
      batch: "28 batch",
      school: "Bhatpiary J.R.S High School",
      scholarship: 43,
      gender: "male",
    },
    {
      // photo: "/images/students/28013.jpg",
      name: "Md. Merajul Islam",
      id: "28013",
      batch: "28 batch",
      school: "Bhatpiary J.R.S High School",
      scholarship: 43,
      gender: "male",
    },
    {
      // photo: "/images/students/28014.jpg",
      name: "Ratri Rani Das",
      id: "28014",
      batch: "28 batch",
      school: "Horina Bagbati Girls High School",
      scholarship: 48,
      gender: "female",
    },
    {
      // photo: "/images/students/28015.jpg",
      name: "Mst. Maria Khatun",
      id: "28015",
      batch: "28 batch",
      school: "Saraitoil High School",
      scholarship: 55,
      gender: "female",
    },
    {
      // photo: "/images/students/28016.jpg",
      name: "Md. Mahmudul Hassan",
      id: "28016",
      batch: "28 batch",
      school: "Tarakandi High School",
      scholarship: 25,
      gender: "male",
    },

    // ———— Screenshot list (28017+) ————
    {
      // photo: "/images/students/28017.jpg",
      name: "Zihad Sarkar",
      id: "28017",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28018.jpg",
      name: "Md. Ariyan Ahmed Manik",
      id: "28018",
      batch: "28 batch",
      school: "Shohid Ahshan Ul Habib High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28019.jpg",
      name: "Tahsin Hasan Rion",
      id: "28019",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28020.jpg",
      name: "Anika Mariya",
      id: "28020",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28021.jpg",
      name: "Imrael Hasan",
      id: "28021",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28022.jpg",
      name: "Md. Shovon Ahmed",
      id: "28022",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28023.jpg",
      name: "Md. Harun Or Roshid",
      id: "28023",
      batch: "28 batch",
      school: "Bahuka High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28024.jpg",
      name: "Boishakhi Akter Mitu",
      id: "28024",
      batch: "28 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28025.jpg",
      name: "Mst. Nushrat Jahan Himi",
      id: "28025",
      batch: "28 batch",
      school: "Horina Bagbati High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28026.jpg",
      name: "Most. Sadia Khatun",
      id: "28026",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28027.jpg",
      name: "Md. Omar Khan",
      id: "28027",
      batch: "28 batch",
      school: "Bhatpeary J.R.S High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28028.jpg",
      name: "Md. Tamzid Tamim",
      id: "28028",
      batch: "28 batch",
      school: "Bhatpeary J.R.S High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28029.jpg",
      name: "Md. Nafis Ahmed",
      id: "28029",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28030.jpg",
      name: "Md. Merajul",
      id: "28030",
      batch: "28 batch",
      school: "Bhatpeary J.R.S High School",
      scholarship: 0,
      gender: "male",
    },
    {
      // photo: "/images/students/28031.jpg",
      name: "Fatema Akter",
      id: "28031",
      batch: "28 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28032.jpg",
      name: "Mst. Sadia Khatun",
      id: "28032",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28033.jpg",
      name: "Mst. Nowrin Afroz",
      id: "28033",
      batch: "28 batch",
      school: "Chilgacha Sherebanu Girls High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28034.jpg",
      name: "Mst. Afifa Khatun",
      id: "28034",
      batch: "28 batch",
      school: "Garudha Shishu Sadan High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/28035.jpg",
      name: "Sayma Jahan Talukder",
      id: "28035",
      batch: "28 batch",
      school: "Boyra Vennabari High School",
      scholarship: 100,
      gender: "female",
    },
    {
      // photo: "/images/students/28036.jpg",
      name: "Sumaiya Akter Riju",
      id: "28036",
      batch: "28 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28037.jpg",
      name: "Most. Tasfiya Lamiya",
      id: "28037",
      batch: "28 batch",
      school: "Boyra Vennabari High School",
      scholarship: 0,
      gender: "female",
    },
    {
      // photo: "/images/students/28038.jpg",
      name: "Mst. Khadija Khatun",
      id: "28038",
      batch: "28 batch",
      school: "Saraitoil High School",
      scholarship: 0,
      gender: "female",
    },
  ],
};

// ===== Export all batches =====
export const allBatches: Batch[] = [batch28, batch27, batch26];

// ===== Helper functions =====
export function getAllStudents(): Student[] {
  return allBatches.flatMap((b) => b.students);
}

export function getBatchByNumber(num: number): Batch | undefined {
  return allBatches.find((b) => b.batchNumber === num);
}

export function getStudentStats() {
  const all = getAllStudents();
  const scholarshipCount = all.filter((s) => s.scholarship >= 50).length;
  const schools = new Set(all.map((s) => s.school)).size;
  const batchesWithStudents = allBatches.filter(
    (b) => b.students.length > 0,
  ).length;

  return {
    totalStudents: all.length,
    scholarshipCount,
    totalSchools: schools,
    totalBatches: allBatches.length,
    activeBatches: batchesWithStudents,
  };
}
